version: '3.2'
services:
  geth:
    image: "matterlabs/geth:latest"
    logging:
        driver: none 
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - geth:/var/lib/geth/data
  postgres-zksync:
    image: "postgres:14"
    logging:
      driver: none 
    volumes:
      - postgres-zksync:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  zksync:
    stdin_open: true
    tty: true
    image: matterlabs/local-node:latest2.0
    depends_on:
      - geth
      - postgres-zksync
    ports:
      - "3050:3050" # JSON RPC HTTP port
      - "3051:3051" # JSON RPC WS port
    volumes:
      # Configs folder bind
      - zksync-config:/etc/env/
      # Storage folder bind
      - zksync-data:/var/lib/zksync/data
    environment:
      - DATABASE_URL=postgres://postgres@postgres-zksync/zksync_local
      - ETH_CLIENT_WEB3_URL=http://geth:8545

volumes:
  geth:
  postgres-zksync:
  zksync-config:
  zksync-data: