version: '3.2'
networks:
  zkstack:
    driver: bridge
services:
  postgres:
    image: "postgres:14"
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: notsecurepassword
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
    networks:
      - zkstack
