version: '3.2'
services:
  geth:
    image: "matterlabs/geth:latest"
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - geth:/var/lib/geth/data
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30
  ipfs:
    image: ipfs/kubo:v0.14.0
    ports:
      - '5001:5001'
    volumes:
      - ipfs:/data/ipfs
  
  postgres-zksync:
    image: "postgres:14"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-zksync:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  postgres-graph:
    image: postgres:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres-graph:/var/lib/postgresql/data
  postgres-explorer:
    image: "postgres:14"
    volumes:
      - postgres-explorer:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=block-explorer
  
  explorer-app:
    image: "matterlabs/block-explorer-app"
    ports:
      - '3010:3010'
    depends_on:
      explorer-api:
        condition: service_started
        restart: true
    volumes:
      - ./.maintain/explorer.config.js:/usr/src/app/packages/app/dist/config.js
  explorer-worker:
    image: "matterlabs/block-explorer-worker"
    environment:
      - PORT=3001
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DATABASE_HOST=postgres-explorer
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=block-explorer
      - BLOCKCHAIN_RPC_URL=http://zksync:3050
      - DATA_FETCHER_URL=http://explorer-data-fetcher:3040
      - BATCHES_PROCESSING_POLLING_INTERVAL=1000
    depends_on:
      zksync:
        condition: service_healthy
        restart: true
  explorer-api:
    image: "matterlabs/block-explorer-api"
    environment:
      - PORT=3020
      - METRICS_PORT=3005
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres-explorer:5432/block-explorer
    ports:
      - '3020:3020'
    depends_on:
      explorer-worker:
        condition: service_started
        restart: true
  explorer-data-fetcher:
    image: "matterlabs/block-explorer-data-fetcher"
    environment:
      - PORT=3040
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - BLOCKCHAIN_RPC_URL=http://zksync:3050
    ports:
      - '3040:3040'
    depends_on:
      zksync:
        condition: service_healthy
        restart: true

  zksync:
    stdin_open: true
    tty: true
    image: matterlabs/local-node:latest2.0
    depends_on:
      geth:
        condition: service_healthy
        restart: true
      postgres-zksync:
        condition: service_healthy
        restart: true
    ports:
      - "3050:3050" # JSON RPC HTTP port
      - "3051:3051" # JSON RPC WS port
    volumes:
      # Configs folder bind
      - zksync-config:/etc/env/
      # Storage folder bind
      - zksync-data:/var/lib/zksync/data
    environment:
      - DATABASE_URL=postgres://postgres@postgres-zksync/zksync_local
      - ETH_CLIENT_WEB3_URL=http://geth:8545
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3071/health"]
      interval: 30s
      timeout: 5s
      retries: 30
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      geth:
        condition: service_healthy
        restart: true
      ipfs:
        condition: service_started
        restart: true
      postgres-graph:
        condition: service_healthy
        restart: true
      zksync:
        condition: service_healthy
        restart: true
    environment:
      postgres_host: postgres-graph
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'zksync-era:http://zksync:3050'
      GRAPH_LOG: info
  portal:
    build:
      context: .
      dockerfile: ./.maintain/Dockerfile.dapp-portal
    ports:
      - "3000:3000"

  deploy-contracts:
    image: node
    volumes:
      - ./contracts:/app
    working_dir: /app
    command: ["bash", "-c", "yarn && yarn compile && yarn deploy --network dockerComposeNode"]
    depends_on:
      geth:
        condition: service_healthy
        restart: true
      zksync:
        condition: service_healthy
        restart: true
    environment:
      # these are all zksync rich accounts
      # we specify these so that users do not need to make their own .env file
      # when they are just trying to run tests / deploy against this stack
      - WALLET_PRIVATE_KEY=0xd293c684d884d56f8d6abd64fc76757d3664904e309a0645baf8522ab6366d9e
      - GOVERNANCE_ADDRESS=0x36615Cf349d7F6344891B1e7CA7C72883F5dc049
      - WHITELIST_ADMIN_ADDRESS=0xa61464658AfeAf65CccaaFD3a512b69A83B77618

  deploy-graph:
    image: node
    volumes:
      - ./:/app
    working_dir: /app/graph
    command: ["bash", "-c", "yarn prepare"]
    depends_on:
      deploy-contracts:
        condition: service_completed_successfully
        restart: true
volumes:
  ipfs:
  geth:
  postgres-explorer:
  postgres-graph:
  postgres-zksync:
  zksync-config:
  zksync-data: