name: checks

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./.devcontainer/install-tools.sh
          yarn
        env:
          SKIP_FOUNDRY: 1
      - name: Lint
        run: |
          yarn fmt
          yarn lint
      - name: Start zksync service
        run: |
          docker compose up zksync &
      - name: Wait for zksync service to be ready
        run: |
          echo "Waiting for zksync to be up..."
          while [ -z "$(docker compose ps --status running zksync --quiet)" ]; do
            echo "zksync is not yet running, waiting..."
            sleep 10
          done
          sleep 30
      - name: Run tests
        run: yarn test