name: checks

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: ./.devcontainer/install-tools.sh
      - name: Lint
        run: forge fmt --check
      - name: Run tests
        run: forge test --zksync