name: checks

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nodlecode/devcontainer-rollup
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Lint
        run: forge fmt --check
      - name: Run tests
        run: forge test
      - name: Debug 1
        if: always()
        run: whereis solc
      - name: Debug 2
        if: always()
        run: ls -alh $HOME/.svm