name: DevContainer

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:

  build:
    name: Build and cache devcontainer image
    runs-on: ubuntu-latest-8-cores

    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up QEMU for multi-architecture builds
      #   uses: docker/setup-qemu-action@v3

      # - name: Setup Docker buildx for multi-architecture builds
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     use: true

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/nodlecode/devcontainer-rollup
          cacheFrom: ghcr.io/nodlecode/devcontainer-rollup
          push: always
          # platform: linux/amd64,linux/arm64
